
language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - tools
  - build-tools-27.0.3  
  - android-27
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - ./gradlew build
before_install:
  - yes | sdkmanager "platforms;android-27"
